### ISSUE TITLE
allow first and next 

### ISSUE THREAD

**Issue by GeraldPape** [tofuSCHNITZEL/wienerlinien#12]
Allow to get both: first and next.

  - platform: wienerlinien
    firstnext: both
    stops:
      - "8641"
      - "8633"

**Comment by waaeel** [comment]
You could just do the following :
```
sensor:
  - platform: wienerlinien
    firstnext: first
    stops:
      - "4418"
  - platform: wienerlinien
    firstnext: next
    stops:
      - "4418"
```
worked for me
