### ISSUE TITLE
not getting any sensors

### ISSUE THREAD

**Issue by wolfgangbures** [tofuSCHNITZEL/wienerlinien#21]
I have tried withthe relase version AND with the beta, but I get no sensors.

I have an included sensors.yaml like this (and restartet HA)

```
 
  - platform: wienerlinien
    firstnext: first
    stops:
      - "141"
      - "160"
      - "143"
      - "5786"
      - "3874"

  - platform: wienerlinien
    firstnext: next
    stops:
      - "141"
      - "160"
      - "143"
      - "5786"
      - "3874"

```
How should I find them?
