### ISSUE TITLE
Can not get it to start on 2022.12.8

### ISSUE THREAD

**Issue by otherguy** [tofuSCHNITZEL/wienerlinien#9]
Hi! I'm using the 2022.12.x (currently 2022.12.8) version of HA (OS) and I can't get the sensor to show up. The configuration is:

```
sensor:
# https://till.mabe.at/rbl/?line=170&station=32615
- platform: wienerlinien
  firstnext: first
  stops:
    - '303'
```

There is nothing in the logs either. I'm on `1.3.0-beta`.

<img width="779" alt="CleanShot 2022-12-22 at 12 07 44@2x" src="https://user-images.githubusercontent.com/6072721/209121458-2fcd3724-36fa-4132-bd6d-4937fc470d6f.png">
